uploads = []
outputs = []

[[generated]]
id = "RjsHEZFtisv686mwWT1-G"
uri = "file://attached_assets/generated_images/generated_image_0.png"
type = "image"
title = "generated_image"

[[generated]]
id = "wqGcugeiK-_gfeOEawOcB"
uri = "file://attached_assets/generated_images/generated_image_1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "QtG5tHClEfydBrQCVL1Q-"
uri = "file://attached_assets/generated_images/generated_image_2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "zVAtOJ7nyqjI7EbZd1ObV"
uri = "file://attached_assets/generated_images/generated_image_3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "2dmURUqCYdzY2EAsZI_0a"
uri = "file://attached_assets/generated_images/generated_image_4.png"
type = "image"
title = "generated_image"
